// Command stdlib-gaps reports how much of each standard library package the
// go2js runtime answers for. It loads the installed Go's export data for a
// package, compares the package-level exported names against the runtime's
// registry, and prints the coverage plus the names that would need wiring up.
// It is the machine behind docs/stdlib-support.md.
package main

import (
	"flag"
	"fmt"
	"go/importer"
	"go/token"
	"os"
	"sort"
	"strings"

	"github.com/zenobiatranoss/go2js/backend/javascript"
)

// identPath maps the registry identifiers that are not themselves import paths
// to the standard library path they stand for. The keys are exactly the
// inventory names that export data cannot be loaded for.
var identPath = map[string]string{
	"atomic":       "sync/atomic",
	"base64":       "encoding/base64",
	"binary":       "encoding/binary",
	"csv":          "encoding/csv",
	"debug":        "runtime/debug",
	"filepath":     "path/filepath",
	"heap":         "container/heap",
	"hex":          "encoding/hex",
	"hmac":         "crypto/hmac",
	"htmltemplate": "html/template",
	"http":         "net/http",
	"json":         "encoding/json",
	"list":         "container/list",
	"md5":          "crypto/md5",
	"rand":         "math/rand",
	"sha1":         "crypto/sha1",
	"sha256":       "crypto/sha256",
	"texttemplate": "text/template",
	"url":          "net/url",
	"utf16":        "unicode/utf16",
	"utf8":         "unicode/utf8",
}

type multiFlag []string

func (m *multiFlag) String() string { return strings.Join(*m, ",") }

func (m *multiFlag) Set(value string) error {
	*m = append(*m, value)
	return nil
}

func main() {
	var targets multiFlag
	flag.Var(&targets, "package", "standard library package to report on; repeatable")
	writeTo := flag.String("write", "", "write the markdown report to this file")
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "usage: go run ./tools/stdlib-gaps [-package import/path]... [-write file.md]\n")
		flag.PrintDefaults()
	}
	flag.Parse()

	inventory := javascript.SupportedStdlibSymbols()

	names := append([]string(nil), targets...)
	if len(names) == 0 {
		names = registryNames(inventory)
	}
	sort.Strings(names)

	rows := make([]row, 0, len(names))
	seen := map[string]bool{}

	for _, name := range names {
		path := importPathFor(name, inventory)
		if seen[path] {
			continue
		}
		seen[path] = true

		exported := exportedNames(path)
		symbols := stringSet(inventory[name])

		covered := intersect(exported, symbols)
		missing := subtract(exported, symbols)
		expected := len(exported)
		percent := 0
		if expected > 0 {
			percent = len(covered) * 100 / expected
		}

		rows = append(rows, row{
			name:       name,
			path:       path,
			covered:    len(covered),
			expected:   expected,
			percent:    percent,
			missing:    missing,
			loadFailed: expected == 0 && len(symbols) == 0,
		})
	}

	report := renderTable(rows)
	footer := renderFooter(rows)

	if *writeTo != "" {
		var body strings.Builder
		body.WriteString("# Standard library support\n\n")
		body.WriteString("> Generated by `go run ./tools/stdlib-gaps -write docs/stdlib-support.md`. Do not edit by hand.\n\n")
		body.WriteString("The tables show, per package, how many of the package-level exported names\n")
		body.WriteString("in the installed Go standard library the go2js runtime \u201cansvers\u201d: functions,\n")
		body.WriteString("types, constants and variables a selector may reach. Coverage counts only\n")
		body.WriteString("names the runtime writes real code for, so a small percentage means the rest\n")
		body.WriteString("of the package is a compile-time error yet.\n\n")
		body.WriteString(report)
		body.WriteString("\n")
		body.WriteString(footer)
		if err := os.WriteFile(*writeTo, []byte(body.String()), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "write:", err)
			os.Exit(1)
		}
	}

	fmt.Print(report)
	fmt.Print(footer)
}

type row struct {
	name       string
	path       string
	covered    int
	expected   int
	percent    int
	missing    []string
	loadFailed bool
}

func registryNames(inventory map[string][]string) []string {
	names := make([]string, 0, len(inventory))
	for name := range inventory {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// importPathFor resolves a registry identifier to the import path the export
// data is loaded from. Unknown names are assumed to be paths already.
func importPathFor(name string, inventory map[string][]string) string {
	if _, known := inventory[name]; known {
		if path, ok := identPath[name]; ok {
			return path
		}
		return name
	}
	return name
}

func exportedNames(path string) map[string]bool {
	pkg, err := importer.ForCompiler(token.NewFileSet(), "gc", nil).Import(path)
	if err != nil {
		return nil
	}

	names := make(map[string]bool)
	for _, name := range pkg.Scope().Names() {
		if token.IsExported(name) {
			names[name] = true
		}
	}

	return names
}

func stringSet(names []string) map[string]bool {
	set := make(map[string]bool, len(names))
	for _, name := range names {
		set[name] = true
	}
	return set
}

func intersect(exported, symbols map[string]bool) []string {
	var out []string
	for name := range exported {
		if symbols[name] {
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out
}

func subtract(exported, symbols map[string]bool) []string {
	var out []string
	for name := range exported {
		if !symbols[name] {
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out
}

const missingShown = 12

func renderTable(rows []row) string {
	var b strings.Builder
	b.WriteString("| package      | covered | total | %      | missing (first few) |\n")
	b.WriteString("| ------------ | ------- | ----- | ------ | ------------------- |\n")

	for _, r := range rows {
		shown := r.missing
		if len(shown) > missingShown {
			shown = shown[:missingShown]
		}
		missing := "none"
		if len(r.missing) > 0 {
			missing = strings.Join(shown, ", ")
			if len(r.missing) > missingShown {
				missing += ", \u2026"
			}
		}

		label := r.name
		if label != r.path {
			label = fmt.Sprintf("%s (`%s`)", r.name, r.path)
		}
		if r.loadFailed {
			label += " *(load failed)*"
		}

		fmt.Fprintf(&b, "| %-12s | %-7d | %-5d | %-5d%% | %s |\n", label, r.covered, r.expected, r.percent, missing)
	}

	return b.String()
}

func renderFooter(rows []row) string {
	covered, expected := 0, 0
	for _, r := range rows {
		covered += r.covered
		expected += r.expected
	}

	var b strings.Builder
	fmt.Fprintf(&b, "**Total: %d of %d package-level exported names (%d%%) covered across %d packages.**\n\n",
		covered, expected, 0, len(rows))
	if expected > 0 {
		b.Reset()
		fmt.Fprintf(&b, "**Total: %d of %d package-level exported names (%d%%) covered across %d packages.**\n",
			covered, expected, covered*100/expected, len(rows))
	}

	return b.String()
}
